#ifndef HIVEMIND_VERSION_H
#define HIVEMIND_VERSION_H

#define HIVEMIND_VERSION_MAJOR 0
#define HIVEMIND_VERSION_MINOR 3
#define HIVEMIND_VERSION_PATCH 0
#define HIVEMIND_VERSION "0.3.0"

#endif // HIVEMIND_VERSION_H